whatwg/participate.whatwg.org

CODEOWNERS
This makes https://github.com/whatwg/sg/issues/13 a little less concerning.
=> Meta: use CODEOWNERS

views/agreement.hbs
In https://github.com/whatwg/participant-data/pull/7, a participant got confused between GitHub "ID" and GitHub "username". We should say username, as that's what GitHub appears to use in most of their UI. The data model still uses "ID", as changing that would be complicated for little benefit.
Also changes the confusing field label "Contact (email)" for individuals to just "Email" as is done for entity contacts.
=> Update some agreement field labels

lib/helpers/github.js
This is a follow-up to 5f17bd7d3386089e52a4e5cf13916d3b9da7c16b which uses the non-deprecated method of authenticating.
=> Update OctoKit usage

lib/get-user-status.js, package-lock.json, package.json
Closes #49 by including the appropriate code updates as well as the dependency bump.
=> Update escape-goat from 1.3.0 to 2.1.0

views/agreement.hbs
During development these were used to spot broken links. They have not been applicable at any time while this application was live.
=> Remove leftover TODO styles

lib/helpers/github.js
20b1121c8efb31b082422dfdf5ae069438fe2284 upgraded @octokit/rest, but missed a change to the public API that would cause the server to fail to start. This corrects that error.
#79 will prevent this from happening, and after happening twice in a row, I'm upping the priority of that one.
=> Fix botched Octokit upgrade

__tests__/pr-webhook.js, __tests__/update-pr.js, lib/pr-webhook.js, lib/update-pr.js
These were missed in 8704ab0909775ca1f6e0a8264718528b3573e6e4 and 33f3eb6ef3a4c0e43a9bc7cec5a52dd14ed15523, and not caught because we only had unit tests, which mocked out the GitHub API.
=> More updates for Octokit breaking changes

__tests__/__snapshots__/get-user-status.js.snap, config.json
This makes them match https://github.com/whatwg/sg/blob/master/Workstreams.md and their only standard.
=> Align Workstreams names with whatwg/sg

lib/helpers/json-github-database.js, lib/server-infra/error-handler.js
This is yet another fallout from 20b1121c8efb31b082422dfdf5ae069438fe2284, which was missed due to our unit tests which mock out the GitHub API.
Closes #92.
=> Fix agreement submission after Octokit upgrade

deploy.sh, package.json
The prepare script is intended for this type of thing:
https://docs.npmjs.com/misc/scripts#prepublish-and-prepare
A non-obvious and seemingly undocumented feature is important here:
`npm install --production` won't run the prepare script. If it did, we
wouldn't need `npm run update-sg` in the deploy.sh script.
Fixes the issue described in https://github.com/whatwg/participate.whatwg.org/pull/113#issuecomment-645262103.
=> Switch from postinstall to prepare script for sg/db.json dependency

__tests__/workstreams.js, lib/get-user-status.js, lib/helpers/workstreams.js, lib/update-pr.js
We probably want to deduplicate the `getShortname()` function? Should we create a workstream module that exports workstreams and these helper methods? I'm also happy for you to take this over as that will probably go a bit quicker.
(I looked at 6a04d97573f343f25f79de993ba6dda4d00f749d to see what needed to be adjusted. It seems like we do want to keep the `id` field for the database. It's just that we cannot use that to map to a repo directly.)
Fixes #159.
=> Workstreams and repositories are not 1:1

__tests__/__fixtures__/push-to-branch.json, __tests__/__fixtures__/push-to-main-meta.json, __tests__/tweet-webhook.js, lib/tweet-webhook.js
I was a bit annoyed at how the test forced me to change the code (by moving the `new Twitter()` construction inside the loop), but it seemed clean enough. The alternative would be changing the test condition to be intentionally more vague: something like
```js
if (Twitter.mock.instances[0]) {
expect(Twitter.mock.instances[0].post).not.toHaveBeenCalled();
}
// Otherwise, it was never constructed, which is also a good outcome.
```
I could go either way.
=> Add more tests for tweet-webhook.js

.deployinclude, .github/workflows/deploy.yml
This should work with the current setup, and keep working after
https://github.com/whatwg/participate.whatwg.org/pull/171.
=> Verify deployment using the /version endpoint

__tests__/integration.js, lib/app.js, lib/server-infra/headers.js
There does not appear to be a way to configure DigitalOcean Apps to
always sent some headers (other than CORS) so built it into the app
directly.
=> Send the appropriate headers as expected by misc-server tests

Dockerfile
See https://github.com/dependabot/dependabot-core/issues/2247 for why this is necessary. Closes #197.
=> Manually bump Node to 14.16.1-buster-slim

Dockerfile
Closes #220. See https://github.com/dependabot/dependabot-core/issues/2247 for why this is necessary.
=> Manually update node:14.17.4-buster-slim

Dockerfile
=> Manually update node:14.17.6-buster-slim

Dockerfile
Closes #235. See dependabot/dependabot-core#2247 for why this is necessary.
=> Manually update to node:14.18.1-buster-slim

.github/workflows/deploy.yml, Dockerfile
Closes #273. See https://github.com/dependabot/dependabot-core/issues/2247 for why this is necessary.
=> Manually update to node:16.15.0-buster-slim

Dockerfile
=> Manually update to node:16.16.0-buster-slim

Dockerfile
=> Manually update to node:16.17.0-buster-slim

__tests__/__snapshots__/get-user-status.js.snap, __tests__/__snapshots__/pr-webhook.js.snap, __tests__/__snapshots__/process-agreement.js.snap, __tests__/__snapshots__/update-pr.js.snap, package-lock.json, package.json
Closes #291. Closes #293.
The Jest update is necessarily manual because the snapshot format changed.
=> Manually update Jest and ESLint

Dockerfile
=> Manually update to node:16.17.1-buster-slim

lib/app.js, lib/server-infra/csp.js, views/agreement-status.hbs, views/agreement.hbs
=> Add strict CSP

layouts/whatwg.hbs, views/agreement-status.hbs, views/entity-agreement-success.hbs, views/individual-agreement-success.hbs
Part of https://github.com/whatwg/whatwg.org/issues/401.
=> Update subheadings from <h2> to <p>

Dockerfile
=>  Manually update to node:18.12.1-buster-slim

Dockerfile
=> Manually update to node:18.16.1-buster-slim

Dockerfile
=> Manually update to node:18.17.0-bookworm-slim

Dockerfile
=> Manually update to node:18.17.1-bookworm-slim

__tests__/process-agreement.js, lib/process-agreement.js, package-lock.json, package.json
It's no longer necessary as UUIDs are built into Node since v14. Closes #365.
=> Remove usage of uuid module

Dockerfile
=> Manually update to node:20.10.0-bookworm-slim

__tests__/__snapshots__/get-user-status.js.snap, config.json, lib/get-user-status.js
It was not clear to me, as a WHATWG spec editor, that verifying a participant was a step I needed to do. Providing a link here, on the page which is linked to from the IPR bot failure, makes it clear that spec editors are empowered and expected to verify individuals and entities, and links to the existing good instructions on how to do so.
=> Link to instructions for unverified individuals and entities

Dockerfile
=> Manually update to node:20.12.2-bookworm-slim

Dockerfile
=> Manually update to node:20.14.0-bookworm-slim

Dockerfile
=> Manually update to node:20.15.0-bookworm-slim

Dockerfile
=> Manually update to node:20.16.0-bookworm-slim

Dockerfile
=> Manually update to node:20.17.0-bookworm-slim

.github/workflows/deploy.yml, Dockerfile
=> Manually update to node:22.11.0-bookworm-slim

Dockerfile
=> Manually update to node:22.16.0-bookworm-slim
