whatwg/participate.whatwg.org

views/index.hbs

Helps with https://github.com/whatwg/meta/issues/43.

Meta: use "good first issue" as label

---

.eslintrc.json
__tests__/process-agreement.js
lib/process-agreement.js
package-lock.json
package.json

Closes #1.
---
Not sure if anyone wants to review this repository's code, but I'll leave it up for a bit in case they do. Hopefully Travis will report in with the passing tests.

Normalize and validate incoming GitHub IDs

---

deploy.sh

(Will merge momentarily, if CI is happy.)

Do not deploy pull requests

---

views/agreement.hbs

Closes #13.
(Will merge if CI is happy.)

Validate backup contact email/GitHub ID on the client side too

---

views/index.hbs

Update the GitHub link to not conditionally 404

---

__tests__/__snapshots__/process-agreement.js.snap
__tests__/process-agreement.js
lib/process-agreement.js

See https://github.com/whatwg/html/pull/3606#issuecomment-378049017.

Allow submitting the agreement with only a single workstream

---

lib/app.js
package-lock.json
package.json

May help with #18, and is probably a good idea anyway.

Perform a graceful server shutdown when asked

---

lib/helpers/github.js
package-lock.json
package.json

Will merge if Travis CI gives the sign-off. (And will monitor for any problems with the live site.)

Upgrade dependencies

---

__tests__/__snapshots__/update-pr.js.snap
__tests__/update-pr.js
lib/update-pr.js

Be more lenient in URLs accepted in PR-update form

---

.eslintrc.json
__tests__/__snapshots__/get-user-status.js.snap
__tests__/get-user-status.js
lib/get-user-status.js
package-lock.json
package.json

Thanks @edent for finding this!
The two commits are best reviewed separately as the second is just some rearranging for clarity.

Escape user input (via query params) properly

---

.eslintrc.json
package-lock.json
package.json

Update ESLint and Handlebars dependencies

---

lib/get-user-status.js
package-lock.json
package.json

Update koa-router and escape-goat dependencies

---

__tests__/integration.js
lib/app.js
package-lock.json
package.json

Add a basic integration test

---

__tests__/process-agreement.js
lib/process-agreement.js
package-lock.json
package.json

Both have had slight public API changes. Closes #83. Closes #85.

Update lolex and uuid dependencies

---

layouts/whatwg.hbs

When someone feels ambitious making this use https://github.com/whatwg/whatwg.org/blob/master/site-template.html would be neat.

Add crossorigin attributes

---

layouts/whatwg.hbs

Helps with https://github.com/whatwg/sg/issues/102.

Remove year from copyright line

---

.github/workflows/deploy.yml
__tests__/__fixtures__/merged-pr.json
__tests__/__fixtures__/pr-from-branch-hook-payload.json
__tests__/__fixtures__/pr-from-branch.json
__tests__/__fixtures__/pr-from-fork-hook-payload.json
__tests__/__fixtures__/pr-from-fork.json
__tests__/__fixtures__/pr-from-main-hook-payload.json
__tests__/pr-webhook.js
lib/pr-webhook.js

Helps with https://github.com/whatwg/meta/issues/174.

Default branch rename

---

__tests__/__snapshots__/get-user-status.js.snap
__tests__/get-user-status.js
__tests__/integration.js
lib/get-user-status.js
lib/pr-webhook.js
lib/routes.js
lib/update-pr.js
views/agreement-status.hbs

Closes #21.
All existing tests pass which is a bit suspicious. Curious if this generally looks good. And help with tests appreciated.

Output PR URL in agreement status if we know it

---

.gitignore
lib/routes.js
package-lock.json
package.json

Helps with #171. Will 404 until the deploy process starts outputting version.txt.

Send version.txt at the /version endpoint

---

Dockerfile
lib/helpers/github.js
package-lock.json
package.json

Manually bump Octokit and Node versions

---

Dockerfile
__tests__/process-agreement.js
package-lock.json
package.json

Closes #205. Closes #206. Closes #208.

Manual dependency updates

---

__tests__/compose-tweet.js
lib/compose-tweet.js

Fix tweeting "(thanks undefined!)"

---

__tests__/integration.js
package-lock.json
package.json

Closes #225.
Will merge if CI passes.

Move from node-fetch to minipass-fetch

---

.github/workflows/deploy.yml

Part of https://github.com/whatwg/sg/issues/171.

Trigger deploy for changes in the whatwg/sg repo

---

.github/workflows/deploy.yml

Followup to https://github.com/whatwg/participate.whatwg.org/pull/250.

Run the Verify Deploy job for repository dispatch

---

.github/dependabot.yml
.github/workflows/deploy.yml

Also check for updates to them in the future

Update GitHub Actions versions used

---

__tests__/tweet-webhook.js
lib/tweet-webhook.js
package-lock.json
package.json

Closes https://github.com/whatwg/meta/issues/274.

Use Twitter API v2

---

.github/workflows/deploy.yml

Ideally these would stay in sync with the Dockerfile, but, that's hard.

Make CI use latest Ubuntu/Node

---

Dockerfile
package-lock.json
package.json

For some reason Dependabot PRs are not merging this month.
Closes #375. Closes #376. Closes #377. Closes #378.

Update Node and dependencies

---

__tests__/integration.js
package-lock.json
package.json

Now that we're on Node v20 this seems to be feasible.

Use built-in fetch() instead of minipass-fetch

---

views/agreement.hbs

Screenshot:
Thanks to @Psychpsyo for this suggestion in https://github.com/whatwg/html/pull/10780#issuecomment-2490598392.

Explain on the agreement that legal name is required
